MainQQGroupTip:
  Enable: true
  Message:
  - '[MyKuQ]加载成功!'
  - '啦啦啦啦'
  #主QQ群 插件加载完成提醒
MainAdminQQGroup: 1008686886
#主QQ群
MainAdminQQ: 1008686886
#主管理人
PlayerJoinMessage:
  Enable: true
  Message: "%player%加入了服务器"
#玩家加入服务器时 发送到Q群里面的话
PlayerQuitMessage:
  Enable: true
  Message: "%player%退出了服务器"
#玩家退出服务器时 发送到Q群里面的话
Check:
  GameCheck:
    Message: "群:"
    #发送至QQ群的检测文本
    SendQQGroupMessage: "%player%>>>%chat%"
    isRemoveColor: true
    Tip:
      Enable: true
      #是否开启发送完毕提示
      Message: "消息发送成功~"
      #发送完毕提示消息
  QQGroupCheck:
    Message: "服:"
    #发送至游戏内的检测文本
    SendGameMessage: "[人工智障]%player%>>>%chat%"
    isIDorName: true
    #为true发送至游戏内就是QQ号 为false发送至游戏内就是QQ群昵称
    isRemoveColor: true
    Tip:
      Enable: true
      #是否开启发送完毕提示
      Message: "消息发送成功~"
      #发送完毕提示消息
ListCommands: "/list"
#群内检测头
ListMessage: "当前在线人数:%online_number%\n玩家列表:%online_player%"
System:
  ListenPort: 12138
  #插件开放的端口
  Ip: "127.0.0.1"
  Port: 5700
  #Http上报地址
Rcon:
  Enable: false
  Ip: "0.0.0.0"
  Port: 19132
  Password: "abcde"
  Private: true
  #只允许私聊使用 还是群聊 私聊都行
  #true为只允许私聊 false为都行
WhiteList:
  Enable: true
  #是否开启
  Check: "申请白名单:"
  #检测头
  Message: "%player%成功申请了白名单~"
  #申请成功提示 %player%为申请的玩家name
PlayerBind:
  Enable: true
  #是否开启
  Check: "绑定:"
  #检测头
  Message: "绑定成功~"
  #绑定成功提示
PlayerInfo:
  Enable: true
  #是否开启
  Check: "我的信息"
  #检测头
  Message:
  - '%player%个人信息'
  - '金币:%money%'
  - '积分:%points%'
  - '状态:%online%'
  - '离线时间:%offline_time%'
  - '首次进服:%first_time%'
  #信息
AdminCommands:
  #管理员指令列表
  White:
    MainCommand: "/White "
    #主指令
    Add: "add "
    #添加
    Del: "del "
    #删除
    List: "list"
    #列表
  Admin:
    MainCommand: "/Admin "
    Add: "add "
    Del: "del "
    List: "list"
  Group:
    MainCommand: "/Group "
    Add: "add "
    Del: "del "
    List: "list"
  Bind:
    MainCommand: "/Bind "
    Add: "add "
    Del: "del "
    List: "list"
PlayerSign:
  Enable: true
  #是否开启
  Check: "签到"
  #检测头
  ExChangeReward:
    '金币':
      Points: 100
      #需要的积分
      Commands:
      - '[CMD]say hellow %player%'
      - '[ACTION]§a2333%player%]10]70]20'
      - '[TITLE]%player%]SubTitle]10]70]20'
      #兑换成功执行的指令
      #%player%玩家变量
      #- '[CMD]后台执行的指令]'
      #- '[TITLE]%player%]SubTitle]10]70]20'
      #- '[TITLE]主标题]副标题]淡入时间]停留时间]淡出时间'
      #- '[CHAT]我进来了啦啦啦'
      #- '[CHAT]玩家发送的指令' #加/就是指令 不加就是消息
      #- '[ACTION]§a2333%player%]10]70]20'
      #- '[ACTION]发送的消息]淡入时间]停留时间]淡出时间'
      #- '233333'
      #- '233333 直接发送此段文字给玩家'
      #- '[Bd]233'
      #- '[Bd]服务器内广播消息'
      #加/就是指令 不加就是发送文字
      #注意[]后不能加空格
    '钻石':
      Points: 100
      #需要的积分
      Commands:
      - '[CMD]say hellow %player%'
      - '[ACTION]§a2333%player%]10]70]20'
      - '[TITLE]%player%]SubTitle]10]70]20'
      #兑换成功执行的指令
      #%player%玩家变量
      #- '[CMD]后台执行的指令]'
      #- '[TITLE]%player%]SubTitle]10]70]20'
      #- '[TITLE]主标题]副标题]淡入时间]停留时间]淡出时间'
      #- '[CHAT]我进来了啦啦啦'
      #- '[CHAT]玩家发送的指令' #加/就是指令 不加就是消息
      #- '[ACTION]§a2333%player%]10]70]20'
      #- '[ACTION]发送的消息]淡入时间]停留时间]淡出时间'
      #- '233333'
      #- '233333 直接发送此段文字给玩家'
      #- '[Bd]233'
      #- '[Bd]服务器内广播消息'
      #加/就是指令 不加就是发送文字
      #注意[]后不能加空格
  ExChangeRewardSetting:
    Title: "兑换商店    你当前积分%points%"
    #%points%当前积分变量
    PointsNotEnough: "积分点不足"
    #积分不足提示
    Success: "兑换%item%成功，花费%points%点积分"
    Item: "物品:%item%  所需积分:%points%"
    #物品介绍
    Confirm: "点击选择购买"
    #按钮坐标得字
  SignReward: "1~100"
  #签到奖励 1~100之间随机数字 包括1 和 100 如果不想随机就填数字
  Message: '签到成功，获得%reward%'
  #签到完成发送得话 %reward%获得多少积分点变量
  AlreadySign: "你今天已经签到了~每日五点刷新签到噢~"
CheckVersion:
  Enable: true
  #开启自动检测更新 不会强制下载
  Time: 86400
  #秒为单位